include:
  - project: 'common/gitlab-ci'
    ref: v0.5.0
    file: '/templates/npm-dockerfile-build.yml'

# Update docker_build's before_script to update the public/v.html file
docker-build:
  before_script:
  - !reference [.docker-config, before_script]
  - !reference [.npm-config, before_script]
  - |
    BUILD_DATE="$(date -R)"
    if [ "$CI_COMMIT_TAG" ]; then
      REF_TYPE="Tag"
      GIT_REF="$CI_COMMIT_TAG"
    else
      REF_TYPE="Branch"
      GIT_REF="$CI_COMMIT_BRANCH"
    fi
    sed -i \
      -e "s%__BUILD_DATE__%$BUILD_DATE%g" \
      -e "s%__GIT_SHA__%$CI_COMMIT_SHA%g" \
      -e "s%__REF_TYPE__%$REF_TYPE%g" \
      -e "s%__GIT_REF__%$GIT_REF%g" \
      public/v.html

dtrack-check:
  stage: source_qa

  before_script:
  - !reference [.docker-config, before_script]
  - !reference [.npm-config, before_script]
  
  script:
  - npm --version
  - npm install -g @fjbarrena/dtrack-cli
  - npm install -g @cyclonedx/bom
  - npm install
  - cyclonedx-bom -o bom.xml
  - dtrack-cli --server https://dtrack.dev.kyso.io --bom-path bom.xml --api-key mhJ7ZcJylUH2WY5cFsU2zs87kH9wLABu --project-name kyso-api --project-version latest --auto-create true

variables:
  DOCKER_BUILDKIT: 1