version: '3.7'

services:
  kyso-mongo:
    image: mongo:latest
    container_name: kyso-mongo
    restart: always
    networks:
      - kyso-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: kadmin
      MONGO_INITDB_ROOT_PASSWORD: ksecret
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  kyso-network: