export enum DiscussionPermissionsEnum {
    READ = 'KYSO_IO_READ_DISCUSSION',
    CREATE = 'KYSO_IO_CREATE_DISCUSSION',
    EDIT = 'KYSO_IO_EDIT_DISCUSSION',
    DELETE = 'KYSO_IO_DELETE_DISCUSSION',
    ADMIN = 'KYSO_IO_ADMIN_DISCUSSION',
}
