name: e2e tests

on:
  push:
    branches:      
      - staging

jobs:
  e2e_tests:
    name: Perform e2e tests locally
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start database containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install 

      - name: Install newman
        run: npm install -g newman 

      - name: Run testing server
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          NODE_ENV: testing
          KYSO_FILES_CLOUDFRONT_URL: ${{ secrets.KYSO_FILES_CLOUDFRONT_URL }}
          DATABASE_URI: mongodb://kysodb:kysodb@localhost/kyso?retryWrites=true&w=majority
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PARSE_MASTER_KEY: ${{ secrets.PARSE_MASTER_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          TEAM_PLAN_MONTHLY: ${{ secrets.TEAM_PLAN_MONTHLY }}
          FREE_TEAM_PLAN_MONTHLY: ${{ secrets.FREE_TEAM_PLAN_MONTHLY }}
          BETA_STRIPE_SECRET_KEY: ${{ secrets.BETA_STRIPE_SECRET_KEY }}
          BETA_FREE_TEAM_PLAN_MONTHLY: ${{ secrets.BETA_FREE_TEAM_PLAN_MONTHLY }}
          AUTH_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
          AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}
          OAUTH_USER_PASSWORD: ${{ secrets.OAUTH_USER_PASSWORD }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_EMAIL_DOMAIN: ${{ secrets.MAILGUN_EMAIL_DOMAIN }}
          SELF_URL: http://localhost.kyso.io:4000
          BITBUCKET_API: https://api.bitbucket.org/2.0
          DATABASE_NAME: kyso
          POPULATE_TEST_DATA: true
          BASE_URL: http://localhost:3000
        run: yarn run start 

      - name: Run e2e_tests 
        env:
          POSTMAN_COLLECTION: 18300179-f1ba0d03-7d80-478a-a978-3a6e8072ad69
          POSTMAN_API_KEY: PMAK-61d5d3d5d29ed66783d2a89b-a8fd6297289ae6fcc551bb605c8fd5b03a
        run: newman run https://api.getpostman.com/collections/$POSTMAN_COLLECTION?apikey=$POSTMAN_API_KEY
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
